import { IDatabase } from "../types";

// Word lists by word count
const wordCountOne: string[] = [
  "accordion",
  "acorn",
  "adapter",
  "adventure",
  "AI",
  "air",
  "AC",
  "airplane",
  "airport",
  "alarm",
  "albatross",
  "album",
  "algae",
  "algorithm",
  "alley",
  "alligator",
  "amber",
  "ambulance",
  "anchor",
  "android",
  "ankle",
  "ant",
  "apartment",
  "apple",
  "aquarium",
  "arena",
  "arm",
  "ash",
  "asparagus",
  "aspirin",
  "asteroid",
  "atlas",
  "atom",
  "attic",
  "avalanche",
  "avenue",
  "avocado",
  "award",
  "backpack",
  "badge",
  "bag",
  "balcony",
  "ball",
  "balloon",
  "banana",
  "bandage",
  "bandana",
  "banner",
  "barbecue",
  "barcode",
  "bark",
  "barn",
  "barnacle",
  "basement",
  "basil",
  "bat",
  "bathroom",
  "bathtub",
  "battery",
  "bay",
  "beach",
  "bear",
  "beaver",
  "bed",
  "bedroom",
  "bee",
  "beef",
  "belt",
  "bicycle",
  "bike",
  "binoculars",
  "bird",
  "biscuit",
  "bison",
  "blanket",
  "bleach",
  "blender",
  "blind",
  "blizzard",
  "blood",
  "blossom",
  "blouse",
  "board",
  "boat",
  "bone",
  "book",
  "bookcase",
  "bookmark",
  "boot",
  "boots",
  "bottle",
  "boulder",
  "bowl",
  "box",
  "bracelet",
  "brain",
  "branch",
  "bread",
  "breeze",
  "brick",
  "bridge",
  "broccoli",
  "brochure",
  "brooch",
  "broom",
  "brush",
  "bucket",
  "bud",
  "buffalo",
  "building",
  "bulb",
  "bulldozer",
  "buoy",
  "bus",
  "bush",
  "butter",
  "butterfly",
  "button",
  "cabbage",
  "cable",
  "cactus",
  "cafe",
  "cake",
  "calculator",
  "calendar",
  "camel",
  "camera",
  "can",
  "candle",
  "canoe",
  "canyon",
  "cap",
  "car",
  "card",
  "carpenter",
  "carrot",
  "castle",
  "cat",
  "cave",
  "caviar",
  "ceiling",
  "cell",
  "cement",
  "certificate",
  "chain",
  "chair",
  "chalk",
  "charcoal",
  "charger",
  "cheese",
  "cheesecake",
  "cheetah",
  "chicken",
  "chimney",
  "chimpanzee",
  "chipmunk",
  "chisel",
  "chocolate",
  "cinema",
  "city",
  "clam",
  "clay",
  "cleaner",
  "cliff",
  "clinic",
  "clock",
  "clog",
  "clothes",
  "cloud",
  "coal",
  "coast",
  "coat",
  "cobbler",
  "cobblestone",
  "cobweb",
  "code",
  "coffee",
  "cold",
  "comb",
  "comet",
  "compass",
  "computer",
  "concert",
  "concrete",
  "conditioner",
  "cone",
  "conference",
  "confetti",
  "container",
  "continent",
  "cookie",
  "coral",
  "couch",
  "country",
  "court",
  "cow",
  "crab",
  "crane",
  "cream",
  "crocodile",
  "crosswalk",
  "crow",
  "cucumber",
  "cup",
  "cupcake",
  "current",
  "curtain",
  "cushion",
  "cutting",
  "cyborg",
  "cyclone",
  "daffodil",
  "dandelion",
  "dark",
  "database",
  "deck",
  "decoration",
  "deer",
  "deodorant",
  "desert",
  "desk",
  "detergent",
  "dewdrop",
  "diamond",
  "diary",
  "dictionary",
  "dishwasher",
  "dock",
  "document",
  "dog",
  "doll",
  "dolphin",
  "door",
  "doorbell",
  "doughnut",
  "dove",
  "dragonfly",
  "drawer",
  "dress",
  "drill",
  "driveway",
  "drone",
  "drought",
  "drum",
  "drumstick",
  "dryer",
  "duck",
  "dune",
  "dustpan",
  "eagle",
  "ear",
  "earbuds",
  "earphones",
  "earring",
  "earrings",
  "earthquake",
  "eel",
  "egg",
  "eggplant",
  "elbow",
  "electricity",
  "elephant",
  "elevator",
  "elk",
  "ember",
  "encyclopedia",
  "energy",
  "engine",
  "engineer",
  "envelope",
  "eraser",
  "eruption",
  "excavator",
  "eye",
  "fabric",
  "factory",
  "fajita",
  "falcon",
  "fan",
  "farm",
  "faucet",
  "feather",
  "fence",
  "fern",
  "ferris",
  "ferry",
  "festival",
  "field",
  "fig",
  "file",
  "finger",
  "fire",
  "firefly",
  "fireplace",
  "firetruck",
  "firewood",
  "fish",
  "fist",
  "flag",
  "flame",
  "flamingo",
  "flash",
  "flashlight",
  "flea",
  "fleece",
  "flip-flop",
  "flood",
  "floor",
  "flounder",
  "flower",
  "fly",
  "flyer",
  "fog",
  "folder",
  "foot",
  "force",
  "forest",
  "fork",
  "fossil",
  "fountain",
  "fox",
  "frame",
  "freezer",
  "fridge",
  "frog",
  "fruit",
  "fuel",
  "gadget",
  "galaxy",
  "gale",
  "gallery",
  "garage",
  "garden",
  "gardenia",
  "garlic",
  "gasoline",
  "gear",
  "germ",
  "gift",
  "giraffe",
  "glacier",
  "glass",
  "glasses",
  "glider",
  "glitter",
  "globe",
  "glove",
  "glow",
  "glowworm",
  "glue",
  "goal",
  "goat",
  "goblet",
  "goggles",
  "goose",
  "gopher",
  "gorilla",
  "gown",
  "gps",
  "grapefruit",
  "grass",
  "grater",
  "gravel",
  "guide",
  "guitar",
  "gust",
  "gym",
  "hail",
  "hair",
  "hammer",
  "hammock",
  "hand",
  "handle",
  "harbor",
  "hardware",
  "hat",
  "hawk",
  "headphones",
  "headset",
  "heart",
  "heat",
  "heater",
  "helicopter",
  "helmet",
  "hen",
  "heron",
  "highway",
  "hill",
  "hippopotamus",
  "hockey",
  "hoe",
  "honey",
  "honeycomb",
  "honeydew",
  "hoodie",
  "horizon",
  "horse",
  "horseradish",
  "hospital",
  "hotel",
  "house",
  "hoverboard",
  "humidity",
  "hummingbird",
  "hurricane",
  "hydrangea",
  "ice",
  "iceberg",
  "icicle",
  "igloo",
  "iguana",
  "iguanodon",
  "incense",
  "infinity",
  "ink",
  "inkling",
  "insect",
  "internet",
  "intersection",
  "intestine",
  "iris",
  "iron",
  "island",
  "ivy",
  "jackal",
  "jacket",
  "jackfruit",
  "jackhammer",
  "jam",
  "jar",
  "jasmine",
  "javelin",
  "jeans",
  "jeep",
  "jellyfish",
  "jet",
  "jewelry",
  "jigsaw",
  "journal",
  "jungle",
  "kale",
  "kaleidoscope",
  "kangaroo",
  "kayak",
  "kelp",
  "kelpie",
  "kettle",
  "key",
  "keyboard",
  "keychain",
  "kidney",
  "kitchen",
  "kite",
  "kiwi",
  "kiwifruit",
  "knee",
  "knife",
  "knight",
  "knob",
  "koala",
  "kryptonite",
  "label",
  "ladder",
  "ladle",
  "lagoon",
  "lake",
  "lamb",
  "lamp",
  "landslide",
  "lane",
  "lantern",
  "laptop",
  "lasagna",
  "lava",
  "lawnmower",
  "leaf",
  "leaflet",
  "lecture",
  "leg",
  "lemon",
  "lemonade",
  "lemur",
  "letter",
  "lever",
  "library",
  "light",
  "lightbulb",
  "lighter",
  "lighthouse",
  "lightning",
  "lilac",
  "lily",
  "lion",
  "liver",
  "living",
  "lizard",
  "lobster",
  "lock",
  "lollipop",
  "loofah",
  "lotion",
  "lotus",
  "luggage",
  "lunar",
  "lung",
  "mackerel",
  "magazine",
  "magnet",
  "mall",
  "manual",
  "map",
  "marble",
  "marigold",
  "marker",
  "market",
  "marmot",
  "marsh",
  "marshmallow",
  "mask",
  "matches",
  "mattress",
  "meadow",
  "medal",
  "medicine",
  "meeting",
  "mermaid",
  "metal",
  "metro",
  "microphone",
  "microwave",
  "milk",
  "mirror",
  "mist",
  "modem",
  "molecule",
  "monitor",
  "monkey",
  "monocle",
  "moon",
  "moonlight",
  "moose",
  "mop",
  "moped",
  "mosquito",
  "moss",
  "moth",
  "motor",
  "motorcycle",
  "mountain",
  "mouse",
  "mousepad",
  "mouth",
  "mud",
  "muffin",
  "mug",
  "muscle",
  "museum",
  "mussel",
  "nail",
  "navigator",
  "necklace",
  "nectar",
  "nectarine",
  "needle",
  "nest",
  "net",
  "network",
  "newspaper",
  "night",
  "nightmare",
  "ninja",
  "nose",
  "notebook",
  "notepad",
  "nut",
  "nutmeg",
  "oak",
  "ocean",
  "octagon",
  "octopus",
  "office",
  "oil",
  "ointment",
  "onion",
  "orange",
  "organ",
  "organizer",
  "ornament",
  "ostrich",
  "otter",
  "oven",
  "owl",
  "oxygen",
  "oyster",
  "package",
  "paddle",
  "painting",
  "palm",
  "pan",
  "panda",
  "pants",
  "paper",
  "paperclip",
  "parachute",
  "park",
  "parrot",
  "party",
  "passport",
  "pasta",
  "path",
  "peacock",
  "peak",
  "pearl",
  "pebble",
  "pedestrian",
  "peeler",
  "pelican",
  "pen",
  "pencil",
  "penguin",
  "penholder",
  "peninsula",
  "peony",
  "pepper",
  "perfume",
  "phone",
  "piano",
  "picture",
  "pie",
  "pier",
  "pig",
  "pigeon",
  "pill",
  "pillow",
  "pin",
  "pine",
  "pineapple",
  "pizza",
  "plain",
  "plane",
  "planet",
  "plaque",
  "plaster",
  "plastic",
  "plate",
  "plateau",
  "platter",
  "playground",
  "pliers",
  "plow",
  "plug",
  "plum",
  "pointer",
  "police",
  "polish",
  "pomegranate",
  "poncho",
  "pond",
  "pool",
  "popcorn",
  "porch",
  "port",
  "postcard",
  "poster",
  "pot",
  "potato",
  "power",
  "prairie",
  "present",
  "printer",
  "projector",
  "protractor",
  "purse",
  "puzzle",
  "pyramid",
  "QR",
  "quail",
  "quartz",
  "quasar",
  "quiche",
  "quicksand",
  "quilt",
  "quince",
  "quiver",
  "quokka",
  "quote",
  "rabbit",
  "raccoon",
  "rack",
  "racket",
  "radio",
  "radish",
  "raft",
  "rag",
  "rail",
  "rain",
  "raincoat",
  "rainforest",
  "rake",
  "raspberry",
  "rat",
  "raven",
  "ray",
  "razor",
  "reflection",
  "reindeer",
  "remote",
  "restaurant",
  "rhinoceros",
  "rhubarb",
  "ribbon",
  "rice",
  "ridge",
  "ring",
  "river",
  "riverbank",
  "riverbed",
  "road",
  "robin",
  "robot",
  "rock",
  "rocket",
  "rollercoaster",
  "roof",
  "rooster",
  "root",
  "rose",
  "router",
  "rug",
  "ruler",
  "safe",
  "safflower",
  "saffron",
  "sail",
  "sailboat",
  "salt",
  "sand",
  "sandal",
  "sandals",
  "sandwich",
  "satellite",
  "savannah",
  "saw",
  "scanner",
  "scarf",
  "school",
  "scissors",
  "scone",
  "scooter",
  "scorpion",
  "scrapbook",
  "screen",
  "screwdriver",
  "sea",
  "seagull",
  "seal",
  "seashell",
  "seed",
  "sensor",
  "server",
  "shade",
  "shadow",
  "shampoo",
  "shark",
  "sharpener",
  "shaver",
  "sheep",
  "shelf",
  "shell",
  "ship",
  "shirt",
  "shoe",
  "shoes",
  "shore",
  "shorts",
  "shoulder",
  "shovel",
  "shower",
  "shrimp",
  "shrub",
  "shutter",
  "sidewalk",
  "sign",
  "signal",
  "sink",
  "skate",
  "skateboard",
  "skin",
  "skirt",
  "sky",
  "sleeping",
  "sleet",
  "slipper",
  "slug",
  "smartphone",
  "smartwatch",
  "smoke",
  "snail",
  "snake",
  "sneaker",
  "snow",
  "snowflake",
  "snowshoe",
  "soap",
  "sock",
  "socket",
  "socks",
  "sofa",
  "software",
  "soil",
  "souvenir",
  "spaceship",
  "spark",
  "sparrow",
  "spatula",
  "speaker",
  "spider",
  "sponge",
  "spoon",
  "sprinkler",
  "squid",
  "squirrel",
  "stadium",
  "stamp",
  "stapler",
  "star",
  "starfish",
  "station",
  "statue",
  "steam",
  "sticker",
  "stomach",
  "stone",
  "stoplight",
  "store",
  "storm",
  "stove",
  "strainer",
  "strawberry",
  "stream",
  "street",
  "string",
  "submarine",
  "subway",
  "sugar",
  "suitcase",
  "sun",
  "sunflower",
  "sunglasses",
  "swamp",
  "swan",
  "sweater",
  "switch",
  "syringe",
  "table",
  "tablet",
  "tag",
  "tank",
  "tape",
  "taxi",
  "tea",
  "teapot",
  "teeth",
  "telephone",
  "telescope",
  "television",
  "tent",
  "theater",
  "thorn",
  "thread",
  "thumb",
  "thunder",
  "tick",
  "ticket",
  "tide",
  "tie",
  "tiger",
  "tire",
  "tissue",
  "toad",
  "toadstool",
  "toaster",
  "toe",
  "tofu",
  "tomato",
  "tongs",
  "tongue",
  "tool",
  "toothbrush",
  "toothpaste",
  "tornado",
  "tortoise",
  "towel",
  "town",
  "track",
  "tractor",
  "traffic",
  "train",
  "tram",
  "transmission",
  "tree",
  "treehouse",
  "trolley",
  "trophy",
  "trout",
  "truck",
  "trumpet",
  "tulip",
  "tunnel",
  "turkey",
  "turtle",
  "twig",
  "typhoon",
  "udon",
  "ukelele",
  "ukulele",
  "umbrella",
  "underwear",
  "unicorn",
  "universe",
  "university",
  "uranium",
  "urn",
  "USB",
  "vacuum",
  "valley",
  "valve",
  "van",
  "vanilla",
  "vase",
  "vault",
  "vegetable",
  "village",
  "vine",
  "violet",
  "violin",
  "vitamin",
  "volcano",
  "voltage",
  "vortex",
  "vulture",
  "waffle",
  "wagon",
  "walkway",
  "wall",
  "wallet",
  "walnut",
  "wardrobe",
  "warehouse",
  "washing",
  "wasp",
  "watch",
  "water",
  "watercress",
  "waterfall",
  "watermelon",
  "wave",
  "weed",
  "whale",
  "wheel",
  "wheelchair",
  "whisk",
  "whistle",
  "whiteboard",
  "wildflower",
  "willow",
  "wind",
  "window",
  "wire",
  "wolf",
  "wood",
  "workshop",
  "worm",
  "wrapping",
  "wreath",
  "wrench",
  "wrist",
  "xenon",
  "xenophobia",
  "xerox",
  "xerus",
  "x-ray",
  "xylophone",
  "yacht",
  "yak",
  "yam",
  "yard",
  "yarn",
  "yellow",
  "yeti",
  "yoke",
  "yonder",
  "yoyo",
  "zebra",
  "zephyr",
  "zinnia",
  "zipline",
  "zipper",
  "zoo",
  "zucchini",
];
const wordCountTwo: string[] = [
  "airplane seat",
  "airplane window",
  "airplane wing",
  "amethyst crystal",
  "apple cider",
  "apple orchard",
  "apple pie",
  "apple tree",
  "arid desert",
  "autumn breeze",
  "autumn leaf",
  "baking tray",
  "balloon flight",
  "balloon ride",
  "bamboo forest",
  "banana peel",
  "banana split",
  "basalt cliff",
  "baseball bat",
  "baseball game",
  "baseball mitt",
  "basketball court",
  "basketball hoop",
  "bay breeze",
  "beach ball",
  "beach sand",
  "beach towel",
  "beach umbrella",
  "beach volleyball",
  "beach wave",
  "bicycle ride",
  "big balloon",
  "big bear",
  "big boat",
  "big chair",
  "big city",
  "big dog",
  "big elephant",
  "big fish",
  "big house",
  "big lion",
  "big table",
  "big tree",
  "big truck",
  "bird feathers",
  "bird nest",
  "birthday balloon",
  "birthday cake",
  "birthday candles",
  "birthday card",
  "birthday gift",
  "birthday hat",
  "birthday party",
  "birthday present",
  "black belt",
  "black bird",
  "black cat",
  "black coffee",
  "black hat",
  "black sheep",
  "black shoes",
  "blazing sun",
  "blue jacket",
  "blue jeans",
  "blue ocean",
  "blue sky",
  "blue water",
  "blue whale",
  "book cover",
  "book shelf",
  "boring movie",
  "brick road",
  "brick wall",
  "bright color",
  "bright day",
  "bright idea",
  "bright lamp",
  "bright light",
  "bright moon",
  "bright rainbow",
  "bright star",
  "bright street",
  "bright sun",
  "broken chair",
  "broken glass",
  "bronze statue",
  "brown bear",
  "brown boots",
  "brown dirt",
  "brown dog",
  "brown soil",
  "brown tree",
  "bubble bath",
  "busy station",
  "busy street",
  "butterfly dance",
  "butterfly effect",
  "butterfly garden",
  "butterfly net",
  "butterfly wing",
  "butterfly wings",
  "butter knife",
  "butter spread",
  "calm lake",
  "campfire glow",
  "campfire smoke",
  "campfire song",
  "campfire warmth",
  "camping gear",
  "camping tent",
  "camping trip",
  "candle flame",
  "candle light",
  "candle wax",
  "candy bar",
  "candy cane",
  "candy floss",
  "candy jar",
  "candy shop",
  "candy wrapper",
  "canvas frame",
  "canyon ridge",
  "cape lookout",
  "cardboard box",
  "car door",
  "carnival ride",
  "carnival tent",
  "carrot cake",
  "castle bridge",
  "castle drawbridge",
  "castle gate",
  "castle moat",
  "castle tower",
  "castle wall",
  "cedar wood",
  "ceramic dish",
  "ceramic tile",
  "cheese grater",
  "cheese pizza",
  "cheese platter",
  "cheese sandwich",
  "cheese wheel",
  "cherry blossom",
  "cherry pie",
  "chess board",
  "chess tournament",
  "chocolate bar",
  "chocolate cake",
  "chocolate chip",
  "chocolate milk",
  "chocolate mint",
  "chocolate sauce",
  "city park",
  "city skyline",
  "city street",
  "clay bowl",
  "clay pot",
  "clay tile",
  "clean shirt",
  "clean table",
  "clean water",
  "clean window",
  "clear sky",
  "clear water",
  "cliff edge",
  "closed book",
  "closed jar",
  "closed lid",
  "closed window",
  "cloud cover",
  "cloud formation",
  "cloud shadow",
  "cloudy horizon",
  "cloudy sky",
  "clown fish",
  "coastal cliff",
  "coconut milk",
  "coffee break",
  "coffee cup",
  "cold air",
  "cold breeze",
  "cold drink",
  "cold freezer",
  "cold fridge",
  "cold ice",
  "cold night",
  "cold river",
  "cold water",
  "cold wind",
  "computer mouse",
  "concrete wall",
  "cookie cutter",
  "cookie dough",
  "cookie jar",
  "cool breeze",
  "cool fan",
  "cool jacket",
  "cotton blanket",
  "cotton candy",
  "cotton pillow",
  "cotton shirt",
  "country road",
  "cowboy hat",
  "crayon box",
  "crystal cave",
  "crystal clear",
  "crystal rock",
  "cupcake frosting",
  "daisy chain",
  "dark alley",
  "dark cave",
  "dark cloud",
  "dark night",
  "dark room",
  "dark shadow",
  "dawn light",
  "deep forest",
  "deep hole",
  "deep river",
  "deep sea",
  "deep well",
  "denim jeans",
  "dense forest",
  "desert cactus",
  "desert dune",
  "desert sunset",
  "desert wind",
  "diamond ring",
  "dim candle",
  "dim glow",
  "dim lamp",
  "dim light",
  "dim room",
  "dim star",
  "dining table",
  "dinosaur bone",
  "dinosaur fossil",
  "dirty floor",
  "dirty mirror",
  "dirty shoe",
  "dirty shoes",
  "dirty socks",
  "dog collar",
  "dog leash",
  "dolphin dive",
  "dragon breath",
  "dragon dance",
  "dragon egg",
  "dragon fire",
  "dragon flight",
  "dragonfly wing",
  "dragonfly wings",
  "dragon fruit",
  "dragon scale",
  "dragon tail",
  "dragon tattoo",
  "drift sand",
  "drift wood",
  "dry air",
  "dry cloth",
  "dry mat",
  "dry paper",
  "dry sand",
  "dry soil",
  "dry towel",
  "dry well",
  "dull blade",
  "dull knife",
  "dull pencil",
  "dull shade",
  "dull spoon",
  "dull tool",
  "dusty trail",
  "electric guitar",
  "elephant herd",
  "elephant ride",
  "elephant trunk",
  "elephant tusk",
  "emerald gem",
  "empty bottle",
  "empty box",
  "empty cup",
  "empty plate",
  "empty road",
  "evening sunset",
  "fabric cloth",
  "fairy wings",
  "farm tractor",
  "fast bike",
  "fast car",
  "fast cheetah",
  "fast horse",
  "fast plane",
  "fast river",
  "fast runner",
  "fast train",
  "feather pillow",
  "fern leaf",
  "ferris wheel",
  "field crops",
  "fire engine",
  "fire extinguisher",
  "firefly glow",
  "fire pit",
  "fire truck",
  "fireworks display",
  "fireworks show",
  "fishing boat",
  "fishing hook",
  "fishing line",
  "fishing lure",
  "fishing net",
  "fishing pole",
  "fishing reel",
  "fishing rod",
  "fishing trip",
  "fish tank",
  "fixed machine",
  "fixed table",
  "flannel blanket",
  "floating leaf",
  "flower bed",
  "flower bouquet",
  "flower garden",
  "flower meadow",
  "flower petals",
  "flower pot",
  "flower stem",
  "flower vase",
  "flowing river",
  "flying kite",
  "foggy morning",
  "foggy street",
  "fog horn",
  "football game",
  "football stadium",
  "forest cabin",
  "forest fire",
  "forest hike",
  "forest path",
  "forest stream",
  "fountain spray",
  "fountain statue",
  "fountain water",
  "fresh air",
  "fresh bread",
  "fresh dew",
  "fresh fruit",
  "frosted glass",
  "frozen lake",
  "frozen pond",
  "frying pan",
  "full basket",
  "full cup",
  "full glass",
  "full jar",
  "funny story",
  "garden bench",
  "garden flower",
  "garden gloves",
  "garden gnome",
  "garden hose",
  "garden path",
  "garden shed",
  "garnet brooch",
  "gentle breeze",
  "gentle rain",
  "giraffe spots",
  "glass cup",
  "glass window",
  "gold coin",
  "golden coin",
  "golden key",
  "golden retriever",
  "golden ring",
  "goldfish bowl",
  "gold ring",
  "grain silo",
  "granite floor",
  "grape vine",
  "grassy hill",
  "gravel road",
  "green apple",
  "green garden",
  "green grass",
  "green hill",
  "green leaf",
  "green tree",
  "guitar pick",
  "guitar riff",
  "guitar solo",
  "guitar string",
  "guitar strings",
  "happy child",
  "happy face",
  "harbor light",
  "hard bench",
  "hard brick",
  "hard chair",
  "hard floor",
  "hard surface",
  "hard wall",
  "harvest moon",
  "hay stack",
  "heavy bag",
  "heavy box",
  "heavy rain",
  "heavy rock",
  "heavy stone",
  "high bridge",
  "high mountain",
  "high wall",
  "hiking boots",
  "hiking path",
  "hiking trail",
  "honey bee",
  "honeycomb design",
  "honey jar",
  "horse saddle",
  "hot air balloon",
  "hot coffee",
  "hot day",
  "hot oven",
  "hot sand",
  "hot soup",
  "hot stove",
  "hot sun",
  "hot tea",
  "iceberg tip",
  "ice cream",
  "ice crystal",
  "ice cube",
  "ice cubes",
  "ice rink",
  "ice skates",
  "icy road",
  "iron gate",
  "iron nail",
  "island lagoon",
  "jade bracelet",
  "jelly beans",
  "jelly donut",
  "jelly fish",
  "jelly sandwich",
  "jungle gym",
  "jungle path",
  "jungle river",
  "jungle vine",
  "jungle vines",
  "kite festival",
  "kite flight",
  "kite flying",
  "kite runner",
  "kite string",
  "knitting yarn",
  "lagoon shore",
  "lake shore",
  "leaf pile",
  "leather belt",
  "leather boots",
  "lemonade stand",
  "light bulb",
  "light drizzle",
  "light feather",
  "lighthouse beam",
  "lightning bolt",
  "light paper",
  "light scarf",
  "light snow",
  "limestone wall",
  "linen sheet",
  "lion roar",
  "log cabin",
  "long line",
  "long path",
  "long road",
  "long rope",
  "long snake",
  "loud bell",
  "loud horn",
  "loud music",
  "loud speaker",
  "loud thunder",
  "loud voice",
  "low fence",
  "low hill",
  "low tunnel",
  "lunar eclipse",
  "maple forest",
  "maple leaf",
  "maple syrup",
  "maple tree",
  "marble column",
  "meadow flower",
  "meadow grass",
  "metal gate",
  "metal roof",
  "midnight snack",
  "moon beam",
  "moonbeam light",
  "moon glow",
  "moon landing",
  "moon light",
  "moonlight glow",
  "moonlight path",
  "moonlight walk",
  "moonlit sky",
  "moon rocks",
  "morning fog",
  "moss stone",
  "mountain bike",
  "mountain cabin",
  "mountain climb",
  "mountain goat",
  "mountain hike",
  "mountain lake",
  "mountain path",
  "mountain peak",
  "mountain range",
  "mountain stream",
  "mountain summit",
  "mountain trail",
  "movie theater",
  "mud brick",
  "muddy boots",
  "muddy field",
  "mushroom cloud",
  "narrow alley",
  "narrow road",
  "narrow stream",
  "narrow trail",
  "new bike",
  "new building",
  "new car",
  "new chair",
  "new gate",
  "new jacket",
  "new magazine",
  "new phone",
  "new shoes",
  "night sky",
  "noisy crowd",
  "noisy market",
  "ocean breeze",
  "ocean tide",
  "ocean view",
  "ocean wave",
  "old book",
  "old car",
  "old clock",
  "old fence",
  "old man",
  "old newspaper",
  "old phone",
  "old road",
  "old tree",
  "old truck",
  "onyx ring",
  "opal stone",
  "open book",
  "open box",
  "open door",
  "open gate",
  "open window",
  "orange carrot",
  "orange chair",
  "orange fruit",
  "orange juice",
  "orange sky",
  "orange sun",
  "orange sunset",
  "orchid flower",
  "paint brush",
  "palm leaf",
  "palm leaves",
  "palm tree",
  "paper airplane",
  "paper bag",
  "paper plane",
  "pearl necklace",
  "pear tree",
  "pebble beach",
  "pebble stone",
  "pencil box",
  "pencil case",
  "pencil drawing",
  "pencil eraser",
  "pencil sharpener",
  "pencil sketch",
  "pencil tip",
  "penguin colony",
  "penguin parade",
  "pepper shaker",
  "piano keys",
  "picnic basket",
  "picnic blanket",
  "pineapple juice",
  "pineapple slice",
  "pine cone",
  "pine tree",
  "pink dress",
  "pink flower",
  "pink ribbon",
  "pink rose",
  "pink shell",
  "pirate hat",
  "pirate ship",
  "pirate treasure",
  "pizza box",
  "plastic bottle",
  "platinum chain",
  "polar bear",
  "polar expedition",
  "polar ice",
  "pool table",
  "popcorn bucket",
  "popcorn machine",
  "porcelain vase",
  "prairie grass",
  "pumpkin patch",
  "pumpkin pie",
  "pumpkin spice",
  "purple balloon",
  "purple flower",
  "purple grape",
  "purple hat",
  "purple plum",
  "purple sunset",
  "puzzle piece",
  "quartz gem",
  "quiet forest",
  "quiet garden",
  "quiet library",
  "quiet night",
  "quiet park",
  "quiet room",
  "quiet street",
  "quiet town",
  "quiet whisper",
  "race car",
  "rainbow bridge",
  "rainbow colors",
  "rainbow sky",
  "rainbow trout",
  "rainforest canopy",
  "rainforest tree",
  "rain puddle",
  "rain shower",
  "rainstorm clouds",
  "rainy day",
  "rainy window",
  "red apple",
  "red balloon",
  "red door",
  "red rose",
  "red truck",
  "reef coral",
  "river bank",
  "river boat",
  "river current",
  "river stone",
  "robot arm",
  "robot brain",
  "robot dance",
  "robot hand",
  "robot leg",
  "robot toy",
  "robot voice",
  "rocket ship",
  "rock garden",
  "rocking chair",
  "roller blade",
  "roller blades",
  "roller coaster",
  "roller derby",
  "roller rink",
  "roller skate",
  "roller skates",
  "rolling fog",
  "rolling hills",
  "rose bouquet",
  "rose garden",
  "rose petals",
  "rose stem",
  "rotten apple",
  "rotten banana",
  "rough cloth",
  "rough sand",
  "rough stone",
  "rough surface",
  "round ball",
  "round button",
  "round clock",
  "round plate",
  "ruby jewel",
  "rural field",
  "rusted pipe",
  "rusty hinge",
  "rusty nail",
  "sad face",
  "sad story",
  "sailboat race",
  "sailboat trip",
  "sandcastle building",
  "sandcastle fun",
  "sandcastle moat",
  "sandy shore",
  "sapphire stone",
  "satin ribbon",
  "savannah plain",
  "school bus",
  "sea shell",
  "seashell collection",
  "seashell hunt",
  "shallow pond",
  "shallow pool",
  "shallow stream",
  "shallow water",
  "shark fin",
  "sharp edge",
  "sharp knife",
  "sharp pencil",
  "sharp scissors",
  "shiny car",
  "shiny coin",
  "shopping cart",
  "short bench",
  "short ladder",
  "short man",
  "short pencil",
  "short queue",
  "short string",
  "short trail",
  "short tree",
  "short tunnel",
  "short walk",
  "short wire",
  "short woman",
  "silent forest",
  "silent night",
  "silent river",
  "silk scarf",
  "silver bracelet",
  "silver coin",
  "silver fork",
  "silver ring",
  "silver spoon",
  "skateboard park",
  "skateboard ramp",
  "skateboard trick",
  "skating rink",
  "skyline view",
  "skyscraper view",
  "slate roof",
  "slow bike",
  "slow boat",
  "slow bus",
  "slow snail",
  "slow turtle",
  "slow walk",
  "slow walker",
  "small bird",
  "small box",
  "small bug",
  "small chair",
  "small dog",
  "small fish",
  "small house",
  "small hut",
  "small kitten",
  "small mouse",
  "small rabbit",
  "small toy",
  "small village",
  "smooth fabric",
  "smooth glass",
  "smooth skin",
  "smooth surface",
  "snowball fight",
  "snowboard ramp",
  "snowboard trick",
  "snow drift",
  "snowfall evening",
  "snow flake",
  "snowflake crystal",
  "snowflake design",
  "snowflake pattern",
  "snow globe",
  "snowman head",
  "snowman nose",
  "snowstorm wind",
  "snowy mountain",
  "snowy owl",
  "snowy peak",
  "soccer ball",
  "soccer bench",
  "soccer captain",
  "soccer cleats",
  "soccer club",
  "soccer coach",
  "soccer fans",
  "soccer field",
  "soccer flag",
  "soccer game",
  "soccer gloves",
  "soccer goal",
  "soccer jersey",
  "soccer match",
  "soccer net",
  "soccer referee",
  "soccer season",
  "soccer shoes",
  "soccer socks",
  "soccer stadium",
  "soccer team",
  "soccer tournament",
  "soccer trophy",
  "soccer uniform",
  "soccer whistle",
  "soda can",
  "soda fountain",
  "soft blanket",
  "soft pillow",
  "soft sand",
  "soft towel",
  "sour lemon",
  "space mission",
  "space rocket",
  "space shuttle",
  "space station",
  "spinning top",
  "spinning wheel",
  "spotted deer",
  "spring blossom",
  "spring rain",
  "square box",
  "square frame",
  "square table",
  "stale bread",
  "stale cake",
  "star cluster",
  "starfish island",
  "starfish shell",
  "starlight night",
  "starlight sky",
  "starry night",
  "starry sky",
  "steel bridge",
  "steep cliff",
  "stone path",
  "stone pillar",
  "storm cloud",
  "storm surge",
  "stormy sky",
  "stormy weather",
  "strawberry jam",
  "strawberry pie",
  "strong arm",
  "strong bridge",
  "strong wind",
  "submarine dive",
  "summer breeze",
  "summer sun",
  "sunflower field",
  "sunflower seeds",
  "sunny beach",
  "sun ray",
  "sunrise glow",
  "sunrise hike",
  "sunrise view",
  "sunset beach",
  "sunset breeze",
  "sunset glow",
  "sunset horizon",
  "sunset sky",
  "surf board",
  "surfing wave",
  "swamp water",
  "swift stream",
  "swimming pool",
  "tall building",
  "tall cactus",
  "tall grass",
  "tall lamp",
  "tall man",
  "tall mountain",
  "tall tree",
  "tame cat",
  "tame dog",
  "teddy bear",
  "tennis ball",
  "tennis court",
  "tennis match",
  "tennis net",
  "tennis racket",
  "tennis serve",
  "tennis shoes",
  "thick blanket",
  "thick book",
  "thick fog",
  "thick rope",
  "thick wall",
  "thin magazine",
  "thin mist",
  "thin paper",
  "thin sheet",
  "thin thread",
  "tidal wave",
  "tide pool",
  "tiger cub",
  "tiger paw",
  "tiger roar",
  "tiger stripes",
  "tiny ant",
  "tiny house",
  "tiny insect",
  "tiny spoon",
  "tiny toy",
  "topaz ring",
  "toy car",
  "train ride",
  "train station",
  "train track",
  "treasure chest",
  "treasure map",
  "tree branch",
  "tree house",
  "treehouse swing",
  "tropical drink",
  "tropical island",
  "tulip bouquet",
  "tulip garden",
  "tulip stem",
  "tundra landscape",
  "turquoise pendant",
  "turtle crawl",
  "turtle pond",
  "turtle shell",
  "twilight sky",
  "urban park",
  "valley floor",
  "velvet cushion",
  "vending machine",
  "video game",
  "village pond",
  "volleyball court",
  "volleyball net",
  "warm coat",
  "warm fire",
  "warm hand",
  "warm meal",
  "warm pool",
  "warm soup",
  "warm sweater",
  "water bottle",
  "waterfall mist",
  "waterfall view",
  "water fountain",
  "watermelon seed",
  "watermelon slice",
  "water park",
  "water slide",
  "wave crash",
  "weak fence",
  "weak signal",
  "wet grass",
  "wet ground",
  "wet paint",
  "wet towel",
  "whale shark",
  "white cloud",
  "white dove",
  "white shirt",
  "white table",
  "wide bridge",
  "wide hat",
  "wide river",
  "wide road",
  "wide smile",
  "wild animal",
  "wild berries",
  "wild deer",
  "wild flower",
  "wild horse",
  "wind chime",
  "wind gust",
  "windmill blades",
  "windy hill",
  "winter coat",
  "wood bench",
  "wooden fence",
  "woolen coat",
  "wool sweater",
  "woven basket",
  "woven rug",
  "yellow bird",
  "yellow bus",
  "yellow flower",
  "yellow sun",
  "yellow taxi",
];
const wordCountThree: string[] = [
  "apple pie slice",
  "baking apple pie",
  "baking banana bread",
  "baking birthday cake",
  "baking bread loaf",
  "baking chocolate chip",
  "baking chocolate cookies",
  "baking chocolate cupcakes",
  "baking fresh bread",
  "baking fresh cookies",
  "baking fruit pie",
  "ballet dancer shoes",
  "banana split dessert",
  "Barack Obama speech",
  "barking little dog",
  "basketball court practice",
  "basketball game night",
  "beach ball game",
  "beach umbrella shade",
  "bicycle ride path",
  "Big Ben clock",
  "birthday cake candles",
  "black and white",
  "blowing birthday balloons",
  "blowing birthday candles",
  "blowing soap bubbles",
  "blue whale migration",
  "boiling water kettle",
  "bouncing basketball pass",
  "bouncing rubber ball",
  "broken glass pieces",
  "brushing messy hair",
  "building bird house",
  "building model airplane",
  "building new house",
  "building sand castle",
  "building stone wall",
  "building tall skyscraper",
  "burning camp fire",
  "burning candle light",
  "buying concert tickets",
  "buying groceries list",
  "camping tent fire",
  "candy cane swirl",
  "carving pumpkin face",
  "carving wooden statue",
  "catching falling leaves",
  "catching fast train",
  "catching fireflies jar",
  "catching fish bait",
  "catching fish net",
  "catching football pass",
  "catching frisbee disc",
  "catching morning bus",
  "catching runaway dog",
  "chasing after ball",
  "chasing fast car",
  "cheering loud crowd",
  "cheering soccer fans",
  "chess board game",
  "chirping morning birds",
  "chocolate chip cookies",
  "chocolate milk shake",
  "chopping firewood logs",
  "chopping wood logs",
  "Christmas tree lights",
  "cleaning bathroom mirror",
  "cleaning bathroom sink",
  "cleaning dirty dishes",
  "cleaning dusty shelves",
  "cleaning dusty windows",
  "cleaning glass windows",
  "cleaning kitchen counter",
  "cleaning spilled milk",
  "cleaning swimming pool",
  "cleaning window glass",
  "climbing rock wall",
  "climbing steep hill",
  "climbing steep mountain",
  "climbing tall ladder",
  "climbing tree branch",
  "closing front door",
  "collecting sea shells",
  "collecting seashells beach",
  "comic book cover",
  "comic strip cartoon",
  "completing jigsaw puzzle",
  "completing school project",
  "cooking breakfast eggs",
  "cooking dinner meal",
  "cooking family dinner",
  "cooking fried rice",
  "cooking gourmet meal",
  "cooking vegetable stew",
  "counting paper money",
  "counting silver coins",
  "counting star points",
  "cracking wooden floor",
  "crashing into wall",
  "crashing ocean waves",
  "cup of coffee",
  "cutting birthday cake",
  "cutting fresh herbs",
  "cutting tree branches",
  "cutting wrapping paper",
  "dancing at prom",
  "dancing at wedding",
  "dancing ballerina shoes",
  "dancing to music",
  "dancing wedding night",
  "decorating birthday cake",
  "decorating Christmas tree",
  "decorating living room",
  "decorating office space",
  "delivering fresh bread",
  "designing new logo",
  "digging sand pit",
  "digging vegetable patch",
  "diving deep ocean",
  "Donald Duck voice",
  "drawing animal sketch",
  "drawing art class",
  "drawing cartoon character",
  "drawing chalk picture",
  "drawing city skyline",
  "drawing colorful pictures",
  "drawing family portrait",
  "drawing treasure map",
  "drinking cold soda",
  "drinking fresh juice",
  "drinking hot cocoa",
  "drinking iced coffee",
  "drinking iced lemonade",
  "drinking ice water",
  "drinking morning coffee",
  "driving delivery van",
  "driving family car",
  "driving family truck",
  "driving long distance",
  "driving off road",
  "driving race car",
  "driving red truck",
  "driving school bus",
  "driving sports car",
  "driving vintage car",
  "driving work truck",
  "dusting wooden shelves",
  "eating chocolate cake",
  "eating fresh berries",
  "eating fruit salad",
  "eating lunch sandwich",
  "eating spaghetti dinner",
  "Eiffel Tower visit",
  "exploring jungle path",
  "famous artist painting",
  "feeding baby bird",
  "feeding backyard birds",
  "feeding backyard squirrels",
  "feeding farm animals",
  "feeding hungry cat",
  "feeding pet dog",
  "feeding pet fish",
  "feeding zoo animals",
  "filling coffee cup",
  "filling glass jar",
  "filling ice tray",
  "filling water balloons",
  "filling water bottle",
  "finding hidden key",
  "fireworks night show",
  "fishing at lake",
  "fishing by river",
  "fishing for trout",
  "fishing net catch",
  "fishing river stream",
  "fishing rod bait",
  "fixing broken bicycle",
  "fixing leaking faucet",
  "flipping notebook pages",
  "flipping pancake batter",
  "flipping pancakes breakfast",
  "flipping through magazine",
  "flying colorful kite",
  "flying high kite",
  "flying kite string",
  "flying paper airplane",
  "flying paper kite",
  "folding bath towels",
  "folding clean laundry",
  "folding laundry clothes",
  "folding laundry pile",
  "folding origami crane",
  "folding paper airplane",
  "folding paper boats",
  "folding paper crane",
  "folding paper napkin",
  "folding paper planes",
  "folding white laundry",
  "football match day",
  "fortune cookie message",
  "french fries ketchup",
  "fried chicken sandwich",
  "frozen ice cream",
  "frying bacon strips",
  "galaxy star cluster",
  "galloping race horse",
  "gathering school supplies",
  "gathering storm clouds",
  "gingerbread man cookies",
  "Golden Gate Bridge",
  "golden retriever puppy",
  "golf club swing",
  "Great Wall hike",
  "grilling barbecue meat",
  "grilling barbecue ribs",
  "grilling chicken barbecue",
  "grilling chicken wings",
  "grilling steak dinner",
  "growing apple tree",
  "growing rose bush",
  "guitar player song",
  "guitar string tune",
  "hanging picture frame",
  "happy birthday party",
  "Harry Potter book",
  "haunted house tour",
  "hidden treasure chest",
  "hiking forest trail",
  "hiking mountain path",
  "hiking mountain trail",
  "holding ice cream",
  "holding shopping bags",
  "Hollywood movie sign",
  "honey bee hive",
  "hosting dinner party",
  "hosting house party",
  "hot air balloon",
  "hugging teddy bear",
  "hunting hidden clues",
  "ice cream truck",
  "ice hockey stick",
  "ice skating rink",
  "Jack o lantern",
  "James Bond movie",
  "jogging around block",
  "jogging on treadmill",
  "jogging through park",
  "juggling colorful balls",
  "jumping high rope",
  "jumping into pool",
  "jumping jack flash",
  "jumping on trampoline",
  "jumping over fence",
  "jumping over hurdle",
  "jumping rope session",
  "knitting baby blanket",
  "knitting winter scarf",
  "knitting wool scarf",
  "knitting wool sweater",
  "laptop computer desk",
  "laughing out loud",
  "laughing small child",
  "Leonardo da Vinci",
  "Leonardo Di Caprio",
  "lifting grocery bags",
  "lifting heavy weights",
  "light bulb idea",
  "lighting camp fire",
  "lighting street lamp",
  "listening soft music",
  "listening to music",
  "loading moving truck",
  "lost and found",
  "Louvre Museum art",
  "magic wand trick",
  "making breakfast pancakes",
  "making family dinner",
  "Mickey Mouse ears",
  "mixing cake batter",
  "mixing cookie dough",
  "mixing fruit salad",
  "mixing pancake batter",
  "mixing salad dressing",
  "Mona Lisa painting",
  "mopping hallway floor",
  "mopping hardwood floors",
  "mopping kitchen floor",
  "Mount Everest climb",
  "movie theater seats",
  "mowing backyard lawn",
  "mowing front lawn",
  "mowing front yard",
  "New York City",
  "Niagara Falls trip",
  "ocean blue wave",
  "opening gift box",
  "opening old book",
  "organizing bookshelf items",
  "organizing desk drawer",
  "organizing family photos",
  "organizing garage tools",
  "organizing kitchen drawer",
  "organizing kitchen pantry",
  "organizing office desk",
  "organizing office files",
  "packing suitcase luggage",
  "packing travel bag",
  "painting art canvas",
  "painting blue sky",
  "painting fence posts",
  "painting flower pot",
  "painting flower vase",
  "painting landscape canvas",
  "painting portrait face",
  "painting room wall",
  "painting sunset view",
  "painting wooden chair",
  "painting wooden fence",
  "panda bear cub",
  "paper airplane contest",
  "paper boat sailing",
  "peanut butter sandwich",
  "peeling fresh oranges",
  "peeling orange skin",
  "peeling orange slices",
  "peeling sweet potatoes",
  "pencil sharpener tool",
  "picking autumn leaves",
  "picking flowers bouquet",
  "picking red apples",
  "picking ripe berries",
  "picking ripe fruit",
  "picking wild flowers",
  "pirate treasure chest",
  "pizza oven fire",
  "pizza slice pepperoni",
  "planting flower garden",
  "planting flower seeds",
  "planting herb garden",
  "planting small tree",
  "planting sunflower seeds",
  "planting tree sapling",
  "planting vegetable garden",
  "planting vegetable seeds",
  "playing board game",
  "playing board games",
  "playing chess game",
  "playing guitar chords",
  "playing guitar solo",
  "playing piano chords",
  "playing piano keys",
  "playing tennis match",
  "plucking guitar string",
  "polar bear habitat",
  "pouring cold water",
  "pouring fresh juice",
  "pouring fresh milk",
  "pouring hot coffee",
  "pumping bicycle tires",
  "pumpkin pie slice",
  "Pyramids of Giza",
  "race car driver",
  "racing sports car",
  "rainbow sky colors",
  "raking autumn leaves",
  "reading adventure book",
  "reading bedtime story",
  "reading comic book",
  "reading history book",
  "reading mystery novel",
  "reading story book",
  "repairing broken chair",
  "repairing broken fence",
  "rick and morty",
  "riding carnival ride",
  "riding city bus",
  "riding fast bicycle",
  "riding fast motorcycle",
  "riding fast rollercoaster",
  "riding merry-go-round",
  "riding mountain bike",
  "riding roller coaster",
  "riding school bus",
  "riding white horse",
  "riding wild horse",
  "roaring loud thunder",
  "roaring tiger growl",
  "rock climbing adventure",
  "roller coaster ride",
  "roller skates ride",
  "rolling down hill",
  "rolling green hills",
  "rowing wooden boat",
  "running fast track",
  "running marathon race",
  "running morning marathon",
  "sailing ship adventure",
  "sailing small boat",
  "sailing wooden boat",
  "sailing wooden ship",
  "salt and pepper",
  "Santa Claus suit",
  "science fiction novel",
  "scrubbing kitchen counter",
  "sewing fabric dress",
  "sewing fabric patch",
  "sewing fabric patches",
  "sewing fabric quilt",
  "sewing wool scarf",
  "shaking cold hands",
  "sharpening kitchen knife",
  "sharpening pencil tip",
  "shopping grocery store",
  "shopping mall trip",
  "shopping online sale",
  "shoveling snow driveway",
  "shoveling snow pile",
  "shuffling playing cards",
  "singing birthday song",
  "singing choir performance",
  "singing happy song",
  "singing holiday carols",
  "singing in shower",
  "singing pop song",
  "sipping green tea",
  "sipping herbal tea",
  "sitting in park",
  "skating across ice",
  "skating ice rink",
  "skating roller blades",
  "sketching city skyline",
  "sketching flower vase",
  "sleeping giant mountain",
  "slicing chocolate cake",
  "slicing ripe tomatoes",
  "snowboarding mountain slope",
  "snowman building activity",
  "snowman winter fun",
  "soccer ball kick",
  "soccer stadium fans",
  "soda can fizz",
  "solving crossword puzzle",
  "solving jigsaw puzzle",
  "solving math puzzle",
  "solving puzzle piece",
  "sorting school papers",
  "space rocket launch",
  "spaghetti meatballs dinner",
  "spinning bicycle wheel",
  "splashing water puddle",
  "stacking cardboard boxes",
  "stacking colorful boxes",
  "stacking poker chips",
  "stacking wooden blocks",
  "stacking wooden crates",
  "Statue of Liberty",
  "sticks and stones",
  "stirring cake batter",
  "subway train ride",
  "sunset beach view",
  "superhero cape costume",
  "surfing ocean waves",
  "sweeping kitchen floor",
  "swimming across river",
  "swimming ocean waves",
  "swimming pool laps",
  "swinging on hammock",
  "swinging wooden bat",
  "swing set seat",
  "Sydney Opera House",
  "taking family photo",
  "taking landscape photograph",
  "taping broken box",
  "tasting delicious dessert",
  "tasting new recipe",
  "tasting sweet candy",
  "tasting sweet honey",
  "tennis racket serve",
  "throwing baseball pitch",
  "throwing basketball hoop",
  "throwing basketball pass",
  "throwing frisbee disc",
  "Tom and Jerry",
  "traffic light signal",
  "trimming garden bushes",
  "tuning guitar strings",
  "tuning piano strings",
  "tying red ribbon",
  "tying shoelaces tight",
  "vacuuming carpet floor",
  "vacuuming car seats",
  "vacuuming living room",
  "video game controller",
  "walking city streets",
  "walking forest trail",
  "walking in park",
  "walking neighborhood dog",
  "walking pet dog",
  "washing dirty car",
  "washing dirty clothes",
  "washing dirty dishes",
  "watching classic movie",
  "watching cooking show",
  "watching evening news",
  "watching football game",
  "watching horror movie",
  "watching kids play",
  "watching ocean waves",
  "watching sports game",
  "watching sunrise view",
  "watching sunset view",
  "watching TV series",
  "watching TV show",
  "water fountain splash",
  "watering garden flowers",
  "watering garden plants",
  "watering house plants",
  "waving goodbye hand",
  "waving to friend",
  "waving white flag",
  "wearing winter coat",
  "wedding cake topper",
  "whistling windy breeze",
  "wild west adventure",
  "winning gold medal",
  "wrapping birthday gift",
  "wrapping birthday present",
  "wrapping Christmas presents",
  "wrapping holiday gift",
  "wrapping holiday gifts",
  "wrapping holiday presents",
  "wrestling championship match",
  "writing class assignment",
  "writing class essay",
  "writing daily journal",
  "writing final draft",
  "writing final report",
  "writing greeting card",
  "writing grocery list",
  "writing invitation card",
  "writing love letter",
  "writing love note",
  "writing love poem",
  "writing pen note",
  "writing poetry book",
  "writing research paper",
  "writing science report",
  "writing short story",
  "writing thank you",
  "writing travel blog",
  "writing travel journal",
  "Yin and Yang",
];

// Database of word lists by their word count
const database: IDatabase = {
  "1": wordCountOne,
  "2": wordCountTwo,
  "3": wordCountThree,
};

// Helper function to shuffle and pick first N elements from an array
const getRandomWords = (list: string[], count: number): string[] => {
  return list.sort(() => Math.random() - 0.5).slice(0, count);
};

const getWordList = (wordCount: number): string[] => {
  // Accumulate word lists based on the word count
  const list = [
    ...database["1"],
    ...(wordCount >= 2 ? database["2"] : []),
    ...(wordCount === 3 ? database["3"] : []),
  ];

  // Return 3 random words from the accumulated list
  return getRandomWords(list, 3);
};

export default getWordList;
